name: ganesha_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  marquee: ^2.3.0
  flutter_dotenv: ^5.2.1
  flutter_form_builder: ^9.5.0
  supabase_flutter: ^2.8.1
  flutter_launcher_icons: ^0.14.2
  http: ^1.2.2
  audioplayers: ^6.1.0 

flutter_launcher_icons:
  image_path: "assets/icon.jpg"
  android: true


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/fondo.jpg
    - assets/Logo.png
    - assets/audio/

